
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: when-authorized
spring:
  config:
    import: "optional:file:.env[.properties]"
  application:
    security:
      jwt:
        refresh-token:
          expiration: ${JWT_REFRESH_EXPIRATION}
        secret-key: ${JWT_SECRET}
        expiration: ${JWT_EXPIRATION}
  jpa:
    hikari:
      connection-timeout: '30000'
      maximum-pool-size: '5'
      minimum-idle: '2'
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: 'true'
        show_sql: 'false'
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    password: ${DB_PASSWORD}
    username: ${DB_USERNAME}
    url: ${DATABASE_URL}
app:
  cors:
    allow-credentials: ${CORS_ALLOW_CREDENTIALS}
    max-age: ${CORS_MAX_AGE}
    allowed-methods: ${CORS_ALLOWED_METHODS}
    allowed-origins: ${CORS_ALLOWED_ORIGINS}
logging:
  level:
    org:
      springframework:
        security: INFO
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: WARN
        SQL: WARN
    root: INFO
  pattern:
    console: '%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
server:
  port: ${PORT}
