management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: when-authorized
spring:
  application:
    security:
      jwt:
        refresh-token:
          expiration: ${JWT_REFRESH_EXPIRATION:7200000}
        secret-key: ${JWT_SECRET}
        expiration: ${JWT_EXPIRATION:7200000}
  jpa:
    hikari:
      connection-timeout: '30000'
      maximum-pool-size: '5'
      minimum-idle: '2'
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: 'true'
        show_sql: 'false'
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    password: ${DB_PASSWORD}
    username: ${DB_USERNAME}
    url: ${DATABASE_URL}
app:
  cors:
    allow-credentials: ${CORS_ALLOW_CREDENTIALS:true}
    max-age: ${CORS_MAX_AGE:3600}
    allowed-methods: ${CORS_ALLOWED_METHODS:GET,POST,PUT,DELETE,OPTIONS,PATCH}
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173}
logging:
  level:
    org:
      springframework:
        security: INFO
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: WARN
        SQL: WARN
    root: INFO
  pattern:
    console: '%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
server:
  port: ${PORT:8080}
